spring:
  application:
    name: aws-secret

  cloud:
    aws:
      secretsmanager:
        region: us-east-1
        endpoint: http://localhost:4566

      sqs:
        enabled: true
        region: us-east-1
        endpoint: http://localhost:4566
        message-queue: ${notifications-queue}


  datasource:
    url: ${jdbc-url}
    username: ${db-user}
    password: ${db-password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  config:
    import: aws-secretsmanager:secret/

